version: '3'

services:
  scylla-node1:
    image: scylladb/scylla
    container_name: scylla-node1
    command: --seeds=scylla-node1,scylla-node2 --smp 2 --memory 4G --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042" # CQL port for the first node
    volumes:
      - scylla_data1:/var/lib/scylla
    restart: unless-stopped
    networks:
      - scylla-network

  scylla-node2:
    image: scylladb/scylla
    container_name: scylla-node2
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla_data2:/var/lib/scylla
    depends_on:
      - scylla-node1
    restart: unless-stopped
    networks:
      - scylla-network

  scylla-node3:
    image: scylladb/scylla
    container_name: scylla-node3
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla_data3:/var/lib/scylla
    depends_on:
      - scylla-node1
    restart: unless-stopped
    networks:
      - scylla-network

networks:
  scylla-network:
    driver: bridge

volumes:
  scylla_data1:
  scylla_data2:
  scylla_data3:
